# Generated by Django 3.1.3 on 2020-12-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0002_auto_20201210_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permiss',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, to='Role.PermissTion', verbose_name='角色权限'),
        ),
    ]
