# Generated by Django 3.1.3 on 2020-12-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0003_auto_20201210_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisstion',
            name='per_desc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='权限描述'),
        ),
        migrations.AlterField(
            model_name='permisstion',
            name='per_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='权限名称'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_desc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='角色描述'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='角色名称'),
        ),
    ]
