# Generated by Django 3.1.3 on 2020-12-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0006_permisstion_path_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisstion',
            name='flag',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='标志位'),
        ),
    ]
