# Generated by Django 3.1.3 on 2020-12-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jhuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jhuser',
            name='real_username',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='真实姓名'),
        ),
    ]
