# Generated by Django 3.1.3 on 2020-12-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0001_initial'),
        ('users', '0003_auto_20201210_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jhuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_id', to='Role.role'),
        ),
    ]
