# Generated by Django 3.1.3 on 2020-12-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201210_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jhuser',
            name='role',
        ),
    ]
