# Generated by Django 3.1.3 on 2020-12-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201210_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jhuser',
            name='del_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
    ]
